ACADEMIC_WEIGHT = 3
EXAM_WEIGHT = 3

STRESS_WEIGHT = 5
ANXIETY_WEIGHT = 5

MOTIVATION_WEIGHT = 3
PHYSICAL_ACTIVITY_WEIGHT = 2
SOCIAL_INTERACTION_WEIGHT = 2

GOOD_SLEEP_MIN = 7
GOOD_SLEEP_MAX = 9
LOW_SLEEP_LIMIT = 5

GOOD_SLEEP_BONUS = 8
LOW_SLEEP_PENALTY = 10